apiVersion: eventstreams.ibm.com/v1beta1
kind: EventStreams
metadata:
  name: dev
  namespace: edademo-dev
spec:
  version: 10.4.0
  license:
    accept: true
    use: CloudPakForIntegrationNonProduction
  requestIbmServices:
    iam: false
    monitoring: false
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  security:
    internalTls: NONE
  strimziOverrides:
    entityOperator: 
      topicOperator: {}
      userOperator: {}
    kafka:
      replicas: 1
      authorization:
        type: runas
      config:
        inter.broker.protocol.version: '2.8'
        interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
        log.cleaner.threads: 6
        log.message.format.version: '2.8'
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 1
        offsets.topic.replication.factor: 1
      listeners:
        plain:
          port: 9092
          type: internal
          tls: false
        external:
          port: 9091
          type: route
          authentication:
            type: scram-sha-512
        tls:
          port: 9094
          authentication:
            type: tls
      metrics: {}
      storage:
        type: ephemeral
    zookeeper:
      replicas: 1
      metrics: {}
      storage:
        type: ephemeral
