apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  namespace: kafka
  name: tls-user
  labels:
    strimzi.io/cluster: my-kafka
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: All
        host: '*'
        type: allow
      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: All
        host: '*'
        type: allow
    type: simple