apiVersion: v1
kind: ConfigMap
metadata:
  name: qs-order-mgr-cm
data:
  APP_VERSION: 0.0.1
  KAFKA_BOOTSTRAP_SERVERS: my-kafka-kafka-bootstrap:9093
  ES_APICURIO_URL: http://my-apicurioregistry-kafkasql-service-kafka.itzroks-671000gkc3-hwnxa1-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-south.containers.appdomain.cloud/apis/registry/v2
  KAFKA_TOPIC_NAME: qs-orders
  KAFKA_SSL_PROTOCOL: TLSv1.2
  KAFKA_SSL_TRUSTSTORE_LOCATION: /deployments/certs/server/ca.p12
  KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
  KAFKA_SSL_KEYSTORE_LOCATION: /deployments/certs/user/user.p12
  KAFKA_SSL_KEYSTORE_TYPE: PKCS12
  KAFKA_SECURITY_PROTOCOL: SSL
  

  