
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: order-ms
  name: order-ms
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: order-ms
  type: ClusterIP
