apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: qs-orders
  labels:
    eventstreams.ibm.com/cluster: dev
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: compact