apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaUser
metadata:
  name: scram-user
  namespace: eda-cos
  labels:
    eventstreams.ibm.com/cluster: dev
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operation: Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operation: Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple