apiVersion: batch/v1
kind: Job
metadata:
  name: cp-ca-secret
  namespace: eda-qs
spec:
  template:
    metadata:
      name: cp-ca-secret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - "if [ -z \"$(kubectl get secret es-demo-cluster-ca-cert -n eda-qs | grep found)\" ]; \
          then kubectl get secret es-demo-cluster-ca-cert -n cp4i-eventstreams -o json \
          | jq -r '.metadata.namespace=\"eda-qs\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink,.metadata.ownerReferences, .metadata.resourceVersion, .metadata.creationTimestamp)'  \
          | kubectl apply -n eda-qs -f - ;\
          else echo already_created; fi"
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: eda-qs-sa
