apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: eda-qs-orders
  namespace: cp4i-eventstreams
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: delete