export KAFKA_SSL_TRUSTSTORE_LOCATION=${CERT_LOCATION}
export KAFKA_SSL_TRUSTSTORE_PASSWORD=${CERT_PASSWORD}
export KAFKA_BOOTSTRAP_SERVERS=${BROKER}
export KAFKA_SCRAM_USERNAME=${SCRAM_USERNAME}
export KAFKA_SCRAM_PASSWORD=${SCRAM_PASSWORD}
export KAFKA_TOPIC=${TOPIC}