apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: eda-qs
  name: secret-mgr
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "create", "watch", "list"]