apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: order-mgr
  name: order-mgr
spec:
  replicas: 1
  selector:
    matchLabes:
      app: order-mgr
  template:
    metadata:
      labels:
        app: order-mgr
    spec:
      containers:
      - name: order-mgr
        image: quay.io/ibmcase/order-mgr
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: order-mgr-cm
        - secretRef:
            name: order-mgr-secret
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /deployments/certs/server
          name: kafka-cert
          readOnly: false
          subPath: ""
        - mountPath: /deployments/certs/user
          name: user-cert
          readOnly: false
          subPath: ""
      serviceAccount: order-mgr
      volumes:
      - name: kafka-cert
        secret:
          defaultMode: 384
          optional: false
          secretName: kafka-cluster-ca-cert
      - name: user-cert
        secret:
          defaultMode: 384
          optional: false
          secretName: tls-user

