apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: order-mgr
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: order-mgr
  name: order-mgr
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: order-mgr
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: order-mgr
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app: order-mgr
  name: order-mgr
spec:
  host: ""
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: order-mgr
