apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: qs-order-ms
  name: qs-order-ms
spec:
  host: ""
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: qs-order-ms