version: '2'
services:
  zookeeper:
    image: quay.io/strimzi/kafka:latest-kafka-2.8.1
    container_name: zookeeper
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: quay.io/strimzi/kafka:latest-kafka-2.8.1
    container_name: kafka
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} \
      --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} \
      --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} \
      --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME} \
      --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://kafka:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  producer:
    image: quay.io/ibmcase/eda-cos-demo
    hostname: storeapp
    container_name: storeapp
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_SECURITY_PROTOCOL: PLAINTEXT
      MP_MESSAGING_OUTGOING_ORDERS_TOPIC: edademo-orders
      JAAS_CFG: ""
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ""
    depends_on:
      - kafka
  kconnect:
    container_name: kconnect
    image: quay.io/strimzi/kafka:latest-kafka-2.8.1 
    ports:
      - 8083:8083
    volumes:
      - ./kustomize/services/kconnect:/tmp
    command: [
      "sh", "-c",
      "export LOG_DIR=/tmp &&
      bin/connect-standalone.sh /tmp/local/standalone.properties /tmp/local/kafka-cos-sink-standalone.properties"
    ]
    depends_on:
      - kafka